/*
 * Generated by XDoclet - Do not edit!
 */

/**
 * Local home interface for ShopBuisnessFacade.
 */
public interface ShopBuisnessFacadeLocalHome
   extends javax.ejb.EJBLocalHome
{
   public static final String COMP_NAME="java:comp/env/ejb/ShopBuisnessFacadeLocal";
   public static final String JNDI_NAME="ShopBuisnessFacadeLocal";

   public ShopBuisnessFacadeLocal create()
      throws javax.ejb.CreateException;

}
